apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
type: Opaque
stringData:
  TOKEN: "8635674583:AAGstQqoxW4u6vl_XSJLgbkB2zsgY953O_0"
  GIGACHAT_KEY: "MDE5ZGExZDctMzU3Ni03ODBhLWI5NTItOTc0NjlmY2E5YmNmOjZlMDQ3M2JlLTg4Y2QtNDQ2Ny1hNjk2LTE1NTU2ODZjMjQ0Zg=="